### PR TITLE
Adding awesome data explorer app.

### PR DESCRIPTION
**Pull request by aliavni**
Hi. This adds Awesome Data Explorer app to the gallery. I tested this PR in my local and run tests with `invoke test.all`

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
When reading this file apd-core\core\ImageProcessing\CADDY-Underwater-Stereo-Vision-Dataset-of-hand-gestures.ym I see the error. I will implement some error handling.

image

```bash
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1561: character maps to <undefined>
Traceback:
  File "c:\repos\private\awesomestreamlit\.venv\lib\site-packages\streamlit\ScriptRunner.py", line 324, in _run_script
    exec(code, module.__dict__)
  File "C:\repos\private\awesomestreamlit\gallery\awesome_data_explorer\awesome_data_explorer.py", line 196, in <module>
    main()
  File "C:\repos\private\awesomestreamlit\gallery\awesome_data_explorer\awesome_data_explorer.py", line 129, in main
    categories_and_files = get_categories_and_file_names()
  File "c:\repos\private\awesomestreamlit\.venv\lib\site-packages\streamlit\caching.py", line 463, in wrapped_func
    return get_or_set_cache()
  File "c:\repos\private\awesomestreamlit\.venv\lib\site-packages\streamlit\caching.py", line 449, in get_or_set_cache
    return_value = func(*args, **kwargs)
  File "C:\repos\private\awesomestreamlit\gallery\awesome_data_explorer\awesome_data_explorer.py", line 42, in get_categories_and_file_names
    data_info = yaml.load(f.read(), Loader=yaml.FullLoader)
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
```

**Comment by aliavni** [comment]
@MarcSkovMadsen thanks for merging this.

Error your are seeing is interesting. The same app is deployed in https://awesome-data-explorer.herokuapp.com/ and CADDY Underwater Stereo-Vision in ImageProcessing topic shows without any problems.

**Comment by MarcSkovMadsen** [comment]
I have released to production. But I get an error message.

I interpret this as I need to install git and add it to the PATH.

image

**Comment by MarcSkovMadsen** [comment]
Hi  @aliavni 

Probably the error is caused by me working locally on Windows.

**Comment by aliavni** [comment]
Hi @MarcSkovMadsen you are correct about the bad git executable issue. I reproduced this in a machine without git installed. Installing git solves this.

**Comment by MarcSkovMadsen** [comment]
Hello world and @aliavni 

I installed git in the Docker container and it solved the problem. The app is now available in the gallery. It's actually the default one :+1: 

I announced it here https://discuss.streamlit.io/t/awesome-streamlit-org-change-log/1414/15 and here https://twitter.com/MarcSkovMadsen/status/1225146901760221184?s=20

If you tweet or share a link on Linkedin please share a link here. Then I will like or share.

If I get the time I would also like to port the app to the gallery at awesome-panel.org. I hope it's ok?

Thanks so much.

image

**Comment by aliavni** [comment]
Thanks for your help bringing it in an promoting @MarcSkovMadsen :) I will post a link when I share it somewhere. Feel free to port it to awesome-panel

**Pull request merged**
