### PR TITLE
Add yahooquery streamlit tutorial

### PR DESCRIPTION
**Pull request by dpguthrie**
The streamlit app I am adding is a demo to a python package I wrote called yahooquery.  It uses an unofficial Yahoo Finance API to grab pretty much any of the data you can see on Yahoo Finance.  I have a demo of the app on heroku, which you can view at yahooquery-streamlit.herokuapp.com.  I realize you already have a yahoo finance app, so if this would be too much of a duplicate, I understand.

Thanks for making this awesome collection of streamlit apps / resources; it truly is an incredible tool.

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
Hi @dpguthrie . I really like the app and is very interested in Finance as I work for traders all day long at orsted.com. 

I don't know the Yahaoo Finance Api that well but I can see from your app, that you can actually get quite some information. I have an idea that one day I will create an app for portfolio construction, (risk) management in Streamlit.

I migh add a few docstring and maybe refactor the app a bit into smaller functions if I need. I have not set it up yet. But normally I have a workflow with pylint and mypy and if the complaim then I cannot deploy before I've fixed things. And they would complain about missing docstrings and too long functions.

**Comment by MarcSkovMadsen** [comment]
@dpguthrie . I have a sister site called awesome-panel.org. Would it be Ok if I also added the app there and sited you as the author?

I like having the two sites because then I and others interesting in the space of analytics apps in Python can compare and contrast different frameworks for that.

**Comment by dpguthrie** [comment]
Yeah, we can definitely refactor.  It was one of those things I put together quickly once I realized how simple it could be to put together an app using Streamlit.  Is that something you'd like me to do before you can add it to your site?  Break into functions, add docstrings, etc.?

You can add the app to your other site as well.  Let me know if you need anything to do that.  Thanks again for this resource.  I stumbled upon Streamlit and then your app about two weeks ago and have been playing around with it ever since.

**Comment by MarcSkovMadsen** [comment]
No I will refactor if it's ok. Its a good way for me to learn about the app and on programming in general. 

But if you have the time it would be valuable if you took a look after the refactor and maybe commented or improved.

I've already started. I had to rename to yahaooquery_app.py because it could not import Ticker from yahooquery when the package and the app had the same name.

Then I've added docstrings and some type hints.

Then I've run pylint :-)


```bash
gallery\yahooquery_app\yahooquery_app.py:82:0: R1260: 'main' is too complex. The McCabe rating is 11 (too-complex)
gallery\yahooquery_app\yahooquery_app.py:82:0: R0914: Too many local variables (16/15) (too-many-locals)
gallery\yahooquery_app\yahooquery_app.py:175:51: W0212: Access to a protected member _ENDPOINTS of a client class (protected-access)
gallery\yahooquery_app\yahooquery_app.py:213:75: W0212: Access to a protected member _PERIODS of a client class (protected-access)
gallery\yahooquery_app\yahooquery_app.py:223:39: W0212: Access to a protected member _INTERVALS of a client class (protected-access)
gallery\yahooquery_app\yahooquery_app.py:229:8: C0103: Variable name "df" doesn't conform to snake_case naming style (invalid-name)
gallery\yahooquery_app\yahooquery_app.py:82:0: R0912: Too many branches (17/12) (too-many-branches)
gallery\yahooquery_app\yahooquery_app.py:82:0: R0915: Too many statements (79/50) (too-many-statements)
```bash

**Comment by dpguthrie** [comment]
Absolutely.  That would definitely be helpful for me as well.  This is actually the first time I've contributed to an open source project, so I, like you, appreciate any opportunity to learn something new.  Just let me know what you need.

**Comment by MarcSkovMadsen** [comment]
Just a comment while working. I think your app is the perfect example on how to make a python package come alive.

I believe we will see a flood wave of that. It's so easy with Streamlit to let the user navigate, select a few attributes and display the output of a function.

**Comment by dpguthrie** [comment]
I think you're absolutely right.  It's so much more intuitive and informative to the user to explore a package in a way like this as opposed to a simple README or a screengrab of Jupyter.  Opportunities seem to be endless!

**Comment by MarcSkovMadsen** [comment]
And its not just for (python) packages. It could be for technical documentation.

Say you write some financial model. Making that model interactive and documented is fantastic.

The same with some of our engineers at Orsted. They could make small apps illustration the perfect layout of a wind farm or how some error on a wind turbine is identified using ML.

**Comment by MarcSkovMadsen** [comment]
And Houston - We have lift off :-)

image

@dpguthrie . The code i've refactored is in the MASTER branch. Feel free to take a look and create an updated pull request if needed. 

I hope you think it's still your app :-) 

I've changed some things due to code quality, a little bit due to my coding preferences and a little bit because I thought it would help communicate the app.

I've also inserted a few comments where I think things could be improved further one day.

Maybe later today I would market it a bit in the Change log at discuss.streamlit.io and on Twitter. Hope that is ok. Feel free to do as well if you are into that promotion stuff :-)

**Comment by MarcSkovMadsen** [comment]
And @dpguthrie . I think your python package is awesome. Congrats on that. If you promote it you could see a huge uptake I think.

**Comment by MarcSkovMadsen** [comment]
I've added some feature request to yahooquery based on my experiences.

image

**Comment by dpguthrie** [comment]
I appreciate all of this so much!  Thanks for the feedback also with the yahooquery package.  I appreciate any and all help I can get and will definitely look at updating based on your requests.  Also, feel free to promote the package / app as much as you’d like.

The code looks much better also.  Didn’t see anything that I would want to change.

**Comment by dpguthrie** [comment]
On second thought (after looking at your feature request to further document the formatted argument), we could update the app to allow the user to toggle between formatted and not so they can see what the data output would look like.  Something like radio buttons in the sidebar?  Let me know what you think.

**Comment by MarcSkovMadsen** [comment]
Great idea with the formatting.

Another idea some day could be to build more of an analytics/ insights application on top of yahooquery. Something inspired by https://finance.yahoo.com/quote/GRUB?p=GRUB&.tsrc=fin-tre-srch. But showcasing the power of python, pandas, python plotting libraries, python ML and Deep Learning libraries. That would be awesome. Maybe something where the the user could upload a file of his holdings and see a risk analysis, performance attribution, investment analysis etc.

**Comment by MarcSkovMadsen** [comment]
@dpguthrie . One think a user would need (I think) is either a way to search for tickers. 

Say I want to see Orsted A/S. if I dont know the ticker how would I easily find it? (Its ORSTED.CO).

**Comment by MarcSkovMadsen** [comment]
@dpguthrie 

I've done some promotion here

https://twitter.com/MarcSkovMadsen/status/1215174748969283584?s=20
https://discuss.streamlit.io/t/awesome-streamlit-org-change-log/1414/12?u=marc
https://www.linkedin.com/feed/update/urn:li:activity:6620939210708840450/

Feel free to share.

**Comment by MarcSkovMadsen** [comment]
I've added "thousands seperator" styling to the dataframe in the Base view.

image

You can find the code and an issue here https://github.com/streamlit/streamlit/issues/956#issue-548387693.

@dpguthrie . I think it would be helpfull to copy the working code from the example and use it in your applications. It's just nice with the thousands separator. It makes the DataFrame much more readable I think.

**Comment by dpguthrie** [comment]
That's really helpful.  I think that would definitely make the streamlit app much more user-friendly.  I'll add that to the app.  Also, if you take a look at the heroku site (yahooquery-streamlit.herokuapp.com) you'll see that I added the formatted argument as another widget to the sidebar.  Now the user can see what kind of data is returned when that argument is passed to Ticker.

**Comment by MarcSkovMadsen** [comment]
FYI. @dpguthrie 

I have started a port of the YahooQuery App to awesome-panel.org so that people can review how Streamlit vs Panel works. 

For more info see https://discourse.holoviz.org/t/awesome-panel-org-change-log/66/10?u=marc

image

**Pull request merged**
