### PR TITLE
initial upload stream example app

### PR DESCRIPTION
**Pull request by R-fred**

### CODE REVIEW

**Comment by R-fred** [comment]
initial pull request to add the stream example app to the gallery.

**Comment by MarcSkovMadsen** [comment]
Hi  @R-fred . Thanks so much. I will take a look ASAP.

**Comment by MarcSkovMadsen** [comment]
Hi @R-fred 

Sorry for not getting back sooner. 

I've been contributing to the release of Panel 0.8.0 and updating the site awesome-panel.org.

Now I have the time. You contribution is awesome. I've played around with it and merged it to my master branch. 

There are some things I will like to suggest

- In the deployed version at awesome-streamlit.org I would like to avoid users creating applications as they could potentially tamper the existing code. So could the app see if the "AWESOME_STREAMLIT_ORG" environment variable is exists. If yes then the new app is not created instead a st.info informs the user what would have happened?
- I can see that if the directory already exists an error is triggered. This should be handled.
image
- Then I think this should be moved into the associated package such that the users can use it via the [awesome-streamlit](https://pypi.org/project/awesome-streamlit/) python package.

**What do you think?**

**Comment by MarcSkovMadsen** [comment]
I announced the contribution in the change log.

https://discuss.streamlit.io/t/awesome-streamlit-org-change-log/1414/14

**Comment by R-fred** [comment]
> Hi @R-fred
> Sorry for not getting back sooner.
> I've been contributing to the release of Panel 0.8.0 and updating the site awesome-panel.org.
> Now I have the time. You contribution is awesome. I've played around with it and merged it to my master branch.
> There are some things I will like to suggest
> 
> In the deployed version at awesome-streamlit.org I would like to avoid users creating applications as they could potentially tamper the existing code. So could the app see if the "AWESOME_STREAMLIT_ORG" environment variable is exists. If yes then the new app is not created instead a st.info informs the user what would have happened?
> I can see that if the directory already exists an error is triggered. This should be handled.
> 
> Then I think this should be moved into the associated package such that the users can use it via the awesome-streamlit python package.
> 
> What do you think?

Hi Marc,
Yeah, that makes sense. I'll make the changes.

**Pull request merged**
